Repository Onemind-Services-LLC/netbox-secrets, pull requests merged in 2023-05, with the labels that each got.

#54 Adds support for NetBox v3.5
  env/netbox.env
  netbox_secrets/__init__.py
  netbox_secrets/api/serializers.py
  netbox_secrets/api/views.py
  netbox_secrets/forms/secrets.py
Labels: type: feature

#51 Fix secret filters
  CHANGELOG.md
  Dockerfile
  netbox_secrets/filtersets.py
  netbox_secrets/forms/secrets.py
  netbox_secrets/migrations/0007_secret__object_repr.py
  netbox_secrets/models/secrets.py
  netbox_secrets/tests/test_filters.py
Labels: type: feature, type: bug

#59 Handled operational error during collectstatic
  CHANGELOG.md
  netbox_secrets/__init__.py
  setup.py
Labels: type: bug

#64 [Fix]: The session wasn't working for other users
  netbox_secrets/api/views.py
Labels: type: bug

#66 PRVB
  CHANGELOG.md
  netbox_secrets/api/views.py
  netbox_secrets/filtersets.py
  netbox_secrets/project-static/package.json
  netbox_secrets/project-static/yarn.lock
  netbox_secrets/templates/netbox_secrets/secret.html
  netbox_secrets/views.py
  setup.py
Labels: type: maintenance
