Repository Onemind-Services-LLC/netbox-secrets, pull requests merged in 2024-01, with the labels that each got.

#107 Update Filtersets and Filterforms with Test Cases
  netbox_secrets/filtersets.py
  netbox_secrets/forms/filterset.py
  netbox_secrets/tests/test_filters.py
Labels: type: feature

#118 Release v1.9.1
  .github/workflows/ci.yml
  CHANGELOG.md
  docker-compose.yml
  docs/rest-api/working-with-secrets.md
  netbox_secrets/admin.py
  netbox_secrets/api/views.py
  netbox_secrets/filtersets.py
  netbox_secrets/forms/filterset.py
  netbox_secrets/models/secrets.py
  netbox_secrets/navigation.py
  netbox_secrets/project-static/src/secrets.ts
  netbox_secrets/static/netbox_secrets/secrets.js
  netbox_secrets/static/netbox_secrets/secrets.js.map
  netbox_secrets/templates/netbox_secrets/inc/secret_actions.html
  netbox_secrets/tests/test_filters.py
  netbox_secrets/tests/test_models.py
  setup.py
  test.sh
Labels: type: maintenance

#119 Release v1.10.0
  .jscpd.json
  .pre-commit-config.yaml
  CHANGELOG.md
  Dockerfile
  README.md
  docs/rest-api/working-with-secrets.md
  netbox_secrets/__init__.py
  netbox_secrets/admin.py
  netbox_secrets/api/views.py
  netbox_secrets/filtersets.py
  netbox_secrets/forms/filterset.py
  netbox_secrets/models/secrets.py
  netbox_secrets/project-static/package.json
  netbox_secrets/project-static/tsconfig.json
  netbox_secrets/views.py
  setup.py
Labels: type: feature

#123 Release v1.10.1
  CHANGELOG.md
  README.md
  netbox_secrets/__init__.py
  setup.py
Labels: type: maintenance

#129 Reverted 8257a03 to fix filtersets
  CHANGELOG.md
  netbox_secrets/filtersets.py
  netbox_secrets/forms/filterset.py
  netbox_secrets/tests/test_filters.py
  setup.py
Labels: type: bug
